#theme: jekyll-theme-slate
remote_theme: "mmistakes/so-simple-theme@3.2.0"
locale: en-US
skin: "/assets/css/skins/dark.css"
title: "Matt's Monty Python Repository"
description: "Home of Monty Python transcripts"
url: "https://zaskem.github.io/montypython-repository"
logo: "/images/pythonlogo.jpg"
google_analytics: "UA-1931908-7"
twitter:
  username: "matt_zaske"
read_time: true
words_per_minute: 200

# Collections
collections:
  sketches:
    output: true
    permalink: /:collection/:path/
  holygrail:
    output: true
    permalink: /:collection/:path/
    sort_by: filmorder
    
# Taxonomy pages
category_archive_path: "/categories#"
tag_archive_path: "/tags#"

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true
  # Sketches defaults
  - scope:
      path: "_sketches"
      type: sketches
    values:
      layout: post
      share: true
  # Holy Grail defaults
  - scope:
      path: "_holygrail"
      type: holygrail
    values:
      layout: post
      share: true

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/matt_zaske
    icon: fab fa-twitter
  - title: Facebook
    url: https://facebook.com/zaskem
    icon: fab fa-facebook
  - title: GitHub
    url: https://github.com/zaskem
    icon: fab fa-github
  - title: Website
    url: https://mzonline.com
    icon: fas fa-globe
